#schema.yml

version 2: 

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: raw data of greenweez products
        columns: 
          - name: products_id
            description: primary key identification
          - name: purchSE_PRICE
            description: purchase price of the product
      - name: sales
        identifier: raw_gz_sales
        description: raw data of greenweez sales
 ##       columns: 
  ##        - name: date_date
    ##        description: date of sale
    ##      - name: orders_id
     ##       description: order id of the sale
     ##     - name: pdt_id
     ##       description: product id of the sale product
     ##     - name: revenue
     ##       description: revenue of the sale
     ##     - name: quantity
     ##       description: quantity of the product sold
      - name: ship
        identifier: raw_gz_ship
        description: raw data of greenweez ship
        columns: 
          - name: orders_id
            description: orders id of the shipped orders
          - name: shipping_fee
            description: shipping fee of the order
          - name: shipping_fee_1
            description: shipping fee 2 of the order
          - name: logCost
            description: cost of the logistic
          - name: ship_Cost
            description: cost of the shipping